version: "3.8"

services: 
  server_blog:
    image: 'nginx:alpine'
    container_name: server_blog
    mem_limit: 512m
    mem_reservation: 128m
    cpus: 0.5
    ports: 
      - '8013:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php_blog:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    container_name: php_blog
    mem_limit: 512m
    mem_reservation: 128m
    cpus: 0.5
    volumes: 
      - ./src:/var/www/html:delegated
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  mysql_blog:
    image: mysql:8.0.33
    container_name: mysql_blog
    mem_limit: 256m
    mem_reservation: 64m
    cpus: 0.25
    env_file: 
      - ./env/mysql.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports: 
      - '3308:3306'
  node_blog:
    image: node:14
    container_name: node_blog
    restart: unless-stopped
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm install && npm run dev
